name: ðŸš€ Release

on:
  workflow_dispatch:

env:
  NODE_VERSION: 20
  PNPM_VERSION: 9

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Verify main branch
        run: |
          if [[ "${{ github.ref_name }}" != "main" ]]; then
            echo "Release can only be done on the main branch."
            exit 1
          fi

      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: true

      - name: Build package
        run: pnpm build

      # ÐšÐ¾Ð¿Ð¸Ñ€ÑƒÐµÐ¼ Ð·Ð°Ñ€Ð°Ð½ÐµÐµ ÑÐ³ÐµÐ½ÐµÑ€Ð¸Ñ€Ð¾Ð²Ð°Ð½Ð½Ñ‹Ð¹ public key Ð² dist
      - name: Copy public key
        run: |
          mkdir -p dist
          cp keys/public.pem dist/public.pem

      - name: Sign package
        working-directory: dist
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          if [[ -z "$PRIVATE_KEY" ]]; then
            echo "Set PRIVATE_KEY secret in GitHub Actions"
            exit 1
          fi

          echo "$PRIVATE_KEY" > private_key.pem
          openssl pkeyutl -sign \
            -inkey private_key.pem \
            -out plugin_package.zip.sig \
            -rawin -in plugin_package.zip
          rm private_key.pem

      - name: Extract version
        id: meta
        working-directory: dist
        run: |
          VERSION=$(unzip -p plugin_package.zip manifest.json | jq -r .version)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Create release
        uses: caido/action-release@v1
        with:
          tag: ${{ steps.meta.outputs.version }}
          commit: ${{ github.sha }}
          body: "Release ${{ steps.meta.outputs.version }}"
          artifacts: |
            dist/plugin_package.zip
            dist/plugin_package.zip.sig
            dist/public.pem
          immutableCreate: true
